[spreadsheet-names]
data = "Sheet1"
filters = "Filters List"

[fancy-colors-test]
baby_pink = [172, 170, 169]
queen_pink = [169, 174, 176]
cherry_blossom = [174, 166, 170]
salmon_pink = [174, 150, 157]
misty_rose = [174, 184, 181]
hot_pink = [174, 134, 162]
amaranth_pink = [171, 155, 163]
cameo_pink = [171, 163, 171]
raspberry_pink = [168, 93, 128]
coral_pink = [172, 141, 143]
magenta = [145, 93, 164]
cerise = [167, 93, 129]
alizarin_crimson = [163, 93, 93]
scarlet = [174, 93, 93]
grape_fruit = [174, 93, 93]
fuchsia = [174, 93, 164]
rose_madder = [168, 93, 93]
guardsman_red = [165, 93, 93]
carmine = [168, 93, 93]
vermillion = [172, 93, 93]
deep_magenta = [145, 93, 164]
wine = [158, 93, 93]
burgundy = [150, 93, 93]
mulberry = [162, 127, 134]
maroon_red = [149, 93, 93]
bisque = [174, 181, 172]
champagne = [174, 186, 179]
magnolia = [174, 191, 191]
navajo = [174, 172, 155]
pale_cadmium_orange = [174, 122, 93]
rose_gold = [172, 163, 153]
naples_yellow_reddish = [174, 181, 93]
khaki = [174, 170, 143]
rajah = [174, 166, 93]
moccasin = [174, 176, 160]
terra_cotta = [163, 129, 105]
peach = [174, 183, 175]
apricot = [174, 180, 154]
cadmium_orange = [174, 109, 93]
chrome_titanate = [174, 174, 93]
clay = [174, 161, 120]
sunset_orange = [171, 93, 93]
paprika = [150, 93, 93]
tangerine = [174, 93, 93]
fawn = [174, 171, 153]
brick = [159, 93, 93]
madder_brown = [157, 93, 93]
alloy_orange = [173, 113, 93]
marmalade = [174, 93, 93]
ivory = [174, 191, 191]
corn_silk = [174, 190, 187]
pale_cadmium_yellow = [174, 185, 93]
lemon_chiffon = [174, 191, 185]
cream = [174, 191, 181]
light_jasmine_yellow = [174, 191, 185]
naples_yellow = [174, 186, 93]
daffodil = [174, 191, 93]
canary_yellow = [174, 191, 93]
lemon = [174, 191, 93]
jasmine_yellow = [174, 185, 93]
sweet_corn = [174, 188, 177]
mimosa = [174, 191, 172]
chrome_yellow = [174, 191, 93]
aureoline_yellow = [174, 188, 93]
sulphur_yellow = [174, 191, 93]
wheat = [174, 187, 179]
deep_chrome_yellow = [174, 191, 93]
gold = [174, 191, 93]
citrine_yellow = [174, 191, 93]
vegas_gold = [174, 166, 129]
antique_gold = [174, 170, 93]
saffron_amboge = [174, 191, 93]
golden_rock = [174, 171, 93]
yellow_ochre = [174, 160, 93]
olive_ochre = [173, 150, 93]
sand = [174, 181, 172]
hazelnut = [174, 170, 153]
vanilla = [174, 191, 183]
beige = [174, 188, 185]
flax = [174, 180, 164]
mauve_brown = [168, 127, 112]
camel = [172, 153, 127]
golden_brown = [170, 141, 93]
burlywood = [172, 163, 133]
tan = [173, 167, 150]
ginger = [171, 141, 93]
caramel = [174, 152, 93]
cinnamon = [169, 135, 93]
bronze = [169, 127, 93]
dark_chocolate = [150, 93, 93]
maple_brown = [161, 113, 93]
pecan = [163, 129, 93]
coyote_brown = [157, 117, 93]
deep_khaki = [170, 141, 110]
burnt_umber = [150, 93, 93]
raw_umber = [130, 93, 93]
chestnut = [149, 93, 93]
van_dyke_brown = [149, 113, 93]
egg_shell = [174, 191, 191]
pear = [174, 191, 93]
lime = [93, 174, 93]
pale_jade = [174, 191, 175]
laurel_green = [169, 174, 148]
mint = [93, 174, 158]
citron = [162, 174, 93]
chartreuse = [174, 191, 93]
yellow_green = [162, 174, 93]
apple_green = [146, 174, 93]
glacious_green = [93, 174, 147]
daquiri_green = [93, 174, 155]
cadmium_green = [93, 174, 93]
shamrock_green = [93, 174, 129]
pale_teal = [93, 174, 174]
straw = [174, 188, 162]
olivine = [155, 174, 93]
leaf_green = [93, 174, 93]
hookers_green = [93, 174, 93]
myrtle_green = [93, 174, 93]
olive = [93, 174, 93]
olive_green = [93, 174, 93]
moss_green = [126, 174, 128]
sap_green = [93, 174, 93]
forest_green = [93, 174, 93]
viridian = [93, 174, 93]
seafoam = [93, 174, 174]
aqua = [93, 174, 174]
pale_sky = [93, 174, 174]
baby_blue = [93, 174, 191]
pale_periwinkle = [93, 174, 191]
powder_blue = [93, 174, 191]
aquamarine = [93, 174, 174]
sky_blue = [93, 174, 191]
cerulean_blue = [93, 93, 174]
cornflower_blue = [93, 93, 174]
marine_blue = [93, 93, 174]
turquoise = [93, 174, 174]
emerald = [93, 174, 93]
capri = [93, 93, 174]
steel_blue = [93, 174, 174]
royal_blue = [93, 93, 174]
air_force_blue = [93, 93, 174]
cobalt_teal = [93, 93, 174]
manganese_blue = [93, 93, 174]
indigo = [93, 93, 174]
coral_blue = [93, 93, 174]
sapphire = [93, 93, 174]
twilight_blue = [93, 93, 174]
lapis_blue = [93, 93, 174]
prussian_blue = [93, 93, 174]
navy = [93, 93, 174]
ultramarine = [93, 93, 174]
heather = [211, 214, 217]
blue_bell = [196, 201, 220]
hyacinth = [201, 203, 225]
pale_orchid = [195, 185, 216]
light_lilac = [222, 201, 216]
pale_lilac_gray = [227, 228, 235]
pale_silver = [226, 230, 231]
light_gainsboro_gray = [221, 222, 218]
platinum = [211, 213, 200]
alabaster = [199, 198, 189]
grayish_lavender = [212, 212, 215]
wisteria = [212, 212, 215]
blue_iris = [170, 171, 199]
lavender = [155, 149, 186]
orchid = [150, 129, 183]
lilac = [171, 115, 144]
dull_blue_violet = [199, 199, 202]
ultramarine_violet = [152, 145, 177]
violet = [131, 110, 166]
red_violet = [142, 80, 142]
purple_lake = [154, 75, 108]
old_lavender = [183, 179, 179]
regalia = [142, 119, 157]
royal_purple = [123, 84, 135]
deep_orchid = [104, 55, 91]
tyrian_purple = [126, 73, 92]
deep_purple = [160, 155, 159]
grape = [118, 98, 125]
dioazine_purple = [87, 66, 85]
corinthian_violet = [78, 47, 67]
quinacridone_violet = [109, 74, 88]
pale_mauve_gray = [219, 221, 226]
silver = [204, 208, 211]
gainsboro = [204, 205, 200]
timberwolf = [197, 190, 174]
deep_alabaster = [215, 212, 204]
mauve_gray = [205, 209, 215]
slate_gray = [165, 166, 165]
stone_gray = [188, 191, 192]
fog_gray = [177, 180, 180]
bone = [177, 164, 140]
lilac_gray = [176, 176, 182]
paynes_gray = [147, 147, 147]
marengo = [126, 121, 113]
battleship_gray = [177, 164, 140]
deep_oatmeal = [226, 225, 218]
graphite = [176, 176, 182]
charcoal = [147, 147, 147]
iron_gray = [126, 119, 103]
taupe = [126, 119, 103]


[fancy-colors]
air_force_blue = [93, 138, 168]
alabaster = [242, 240, 230]
alizarin_crimson = [219, 45, 67]
alloy_orange = [196, 66, 16]
amber = [255, 191, 0]
amaranth_pink = [241, 156, 203]
antique_gold = [203, 153, 117]
apple_green = [166, 214, 158]
apricot = [251, 206, 177]
aqua = [0, 255, 255]
aquamarine = [127, 255, 212]
aureoline_yellow = [253, 238, 0]
baby_blue = [137, 207, 240]
baby_pink = [244, 194, 194]
battleship_gray = [132, 132, 130]
beige = [245, 245, 220]
bisque = [255, 228, 196]
blue_bell = [162, 162, 208]
blue_iris = [138, 43, 226]
bone = [227, 218, 201]
brick = [203, 65, 84]
bronze = [205, 127, 50]
burgundy = [128, 0, 32]
burnt_umber = [138, 51, 36]
burlywood = [222, 184, 135]
cadmium_green = [0, 107, 60]
cadmium_orange = [237, 134, 45]
cameo_pink = [239, 187, 204]
camel = [193, 154, 107]
canary_yellow = [255, 239, 0]
capri = [0, 255, 255]
caramel = [255, 213, 79]
carmine = [150, 0, 24]
cerise = [222, 49, 99]
cerulean_blue = [42, 82, 190]
champagne = [247, 231, 206]
charcoal = [54, 69, 79]
chartreuse = [127, 255, 0]
cherry_blossom = [255, 183, 197]
chestnut = [149, 69, 53]
chrome_titanate = [234, 154, 59]
chrome_yellow = [255, 168, 0]
cinnamon = [205, 96, 126]
citrine_yellow = [228, 217, 11]
citron = [159, 169, 31]
clay = [178, 132, 123]
cobalt_teal = [0, 175, 175]
cobalt_violet = [119, 0, 255]
coral_blue = [0, 206, 209]
coral_pink = [248, 131, 121]
corn_silk = [255, 248, 220]
cornflower_blue = [100, 149, 237]
coyote_brown = [129, 97, 60]
cream = [255, 253, 208]
daffodil = [255, 255, 49]
daquiri_green = [173, 255, 47]
dark_chocolate = [92, 64, 51]
dark_slate_grey = [47, 79, 79]
deep_alabaster = [237, 234, 222]
deep_chrome_yellow = [255, 217, 0]
deep_khaki = [189, 183, 107]
deep_magenta = [255, 20, 147]
deep_oatmeal = [245, 245, 220]
deep_orchid = [142, 58, 130]
deep_purple = [63, 0, 127]
dull_blue_violet = [138, 127, 194]
dioazine_purple = [115, 0, 255]
egg_shell = [240, 234, 214]
emerald = [80, 200, 120]
fawn = [229, 170, 112]
flax = [238, 220, 130]
fog_gray = [192, 192, 192]
forest_green = [34, 139, 34]
fuchsia = [255, 0, 255]
gainsboro = [220, 220, 220]
ginger = [255, 99, 71]
glacious_green = [173, 255, 47]
gold = [165, 124, 0]
golden_brown = [153, 101, 21]
grape = [111, 45, 168]
grape_fruit = [255, 99, 71]
graphite = [54, 69, 79]
guardsman_red = [183, 65, 14]
hazelnut = [165, 42, 42]
heather = [214, 202, 221]
hookers_green = [79, 121, 107]
hyacinth = [147, 112, 219]
indigo = [75, 0, 130]
iron_gray = [85, 93, 97]
ivory = [255, 255, 240]
jade = [0, 168, 107]
jasmine_yellow = [255, 255, 102]
jet = [52, 52, 52]
jet_blue = [40, 40, 52]
jet_green = [40, 52, 40]
jet_red = [52, 40, 40]
khaki = [194, 178, 128]
lapis_blue = [38, 97, 156]
laurel_green = [169, 186, 157]
lavender = [230, 230, 250]
leaf_green = [153, 205, 51]
lemon = [255, 247, 0]
lemon_chiffon = [255, 250, 205]
light_gainsboro_gray = [220, 220, 220]
light_jasmine_yellow = [255, 255, 102]
light_lilac = [211, 182, 255]
lilac = [200, 162, 200]
lilac_gray = [200, 162, 200]
lime = [0, 255, 0]
madder_brown = [192, 64, 0]
magnolia = [242, 232, 215]
mandarin = [243, 122, 72]
manganese_blue = [0, 103, 164]
maple_brown = [128, 0, 0]
marengo = [109, 103, 102]
marine_blue = [0, 128, 128]
marmalade = [255, 165, 0]
maroon_red = [128, 0, 0]
mauve_brown = [160, 181, 181]
mauve_gray = [160, 181, 181]
mimosa = [255, 255, 102]
mint = [102, 204, 153]
misty_rose = [255, 228, 225]
moccasin = [255, 218, 185]
moss_green = [138, 154, 91]
mulberry = [197, 75, 140]
myrtle_green = [49, 120, 115]
navajo = [255, 222, 173]
navy = [0, 0, 128]
old_lavender = [169, 105, 144]
olive = [128, 128, 0]
olive_ochre = [128, 128, 0]
olivine = [154, 185, 115]
orchid = [218, 112, 214]
pale_cadmium_orange = [255, 160, 122]
pale_jade = [169, 245, 205]
pale_lilac_gray = [200, 162, 200]
pale_mauve_gray = [200, 162, 200]
pale_orchid = [224, 130, 224]
pale_periwinkle = [204, 204, 255]
pale_sky = [135, 206, 235]
pale_teal = [175, 238, 238]
paprika = [255, 99, 71]
paynes_gray = [83, 104, 120]
peach = [255, 229, 180]
pear = [209, 226, 49]
pecan = [153, 101, 21]
platinum = [229, 228, 226]
powder_blue = [176, 224, 230]
prussian_blue = [0, 49, 83]
purple_lake = [128, 0, 128]
quinacridone_violet = [123, 63, 0]
rajah = [251, 171, 96]
raspberry_pink = [255, 0, 106]
raw_umber = [130, 102, 68]
red_violet = [199, 21, 133]
regalia = [82, 45, 128]
rose_gold = [183, 111, 122]
rose_madder = [233, 16, 65]
royal_blue = [65, 105, 225]
royal_purple = [118, 81, 169]
sap_green = [80, 125, 42]
saffron_amboge = [244, 196, 48]
salmon_pink = [255, 145, 164]
sand = [194, 178, 128]
sapphire = [15, 82, 186]
scarlet = [255, 36, 0]
seafoam = [127, 255, 212]
shamrock_green = [0, 158, 96]
silver = [192, 192, 192]
slate_gray = [112, 128, 144]
stone_gray = [128, 128, 128]
straw = [228, 217, 111]
steel_blue = [70, 130, 180]
sulphur_yellow = [255, 255, 0]
sunset_orange = [255, 94, 83]
sweet_corn = [255, 255, 102]
tan = [210, 180, 140]
tangerine = [255, 133, 0]
taupe = [72, 60, 50]
terra_cotta = [226, 114, 91]
timberwolf = [219, 215, 210]
twilight_blue = [105, 105, 205]
tyrian_purple = [102, 2, 60]
ultramarine = [63, 0, 255]
ultramarine_violet = [119, 0, 255]
van_dyke_brown = [102, 66, 40]
vanilla = [243, 229, 171]
vegas_gold = [197, 179, 88]
vermillion = [230, 66, 52]
viridian = [65, 130, 109]
violet = [143, 0, 255]
wine = [114, 47, 55]
wisteria = [201, 160, 220]
yellow_ochre = [234, 126, 33]


[primary-colors]
pink = [255, 192, 203]
red = [255, 0, 0]
maroon = [128, 0, 0]
orange = [255, 165, 0]
yellow = [255, 255, 0]
gold = [255, 215, 0]
light_green = [144, 238, 144]
green = [0, 128, 0]
olive_green = [128, 128, 0]
dark_green = [0, 100, 0]
aqua = [0, 255, 255]
light_blue = [173, 216, 230]
blue = [0, 0, 255]
navy = [0, 0, 128]
purple = [128, 0, 128]
lavender = [230, 230, 250]
black = [0, 0, 0]
grey = [128, 128, 128]
white = [255, 255, 255]
off_white = [250, 250, 240]
tan = [210, 180, 140]
brown = [165, 42, 42]
